version: '3.7'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak
    #environment:
    #  - KEYCLOAK_ADMIN=test
    #  - KEYCLOAK_ADMIN_PASSWORD=test
    depends_on:
      - postgresql
    ports:
      - "8000:8080"
    volumes:
      - ./theme:/opt/bitnami/keycloak/themes:ro
      #- db-data:/opt/bitnami/keycloak/data

volumes:
  postgresql_data:
    driver: local
